# Generated by Django 6.0.2 on 2026-02-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='contract',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.suppliercontract', verbose_name='договор поставки'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='created_from_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplierproductrequest', verbose_name='создан из заявки'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='created_from_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.productsuppliersource', verbose_name='источник создания'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='поставщик'),
        ),
        migrations.AddField(
            model_name='product',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.suppliercontract', verbose_name='договор поставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_from_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='suppliers.supplierproductrequest', verbose_name='создан из заявки'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_from_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.productsuppliersource', verbose_name='источник создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='поставщик'),
        ),
    ]
