# Generated by Django 6.0.2 on 2026-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_historicalproduct_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='external_url',
            field=models.URLField(blank=True, help_text='Ссылка на товар на внешнем сайте', null=True, verbose_name='внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'В архиве'), ('out_of_stock', 'Нет в наличии')], default='draft', max_length=20, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='warehouse_date',
            field=models.DateField(blank=True, help_text='Дата когда товар поступил на склад. Используется для расчёта скидки.', null=True, verbose_name='дата поступления на склад'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='Ссылка на товар на внешнем сайте', null=True, verbose_name='внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'В архиве'), ('out_of_stock', 'Нет в наличии')], default='draft', max_length=20, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_date',
            field=models.DateField(blank=True, help_text='Дата когда товар поступил на склад. Используется для расчёта скидки.', null=True, verbose_name='дата поступления на склад'),
        ),
    ]
