# Generated by Django 6.0.2 on 2026-02-17 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_historicalproduct_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок слайда')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='slider/%Y/%m/%d', verbose_name='изображение слайдера')),
                ('link', models.URLField(blank=True, help_text='Ссылка при нажатии на слайд', verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_images', to='products.product', verbose_name='связанный товар')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайды',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
