# Generated by Django 6.0.2 on 2026-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена для отображения скидки', max_digits=10, null=True, verbose_name='старая цена'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена товара на слайде. Если указан товар, используется цена товара.', max_digits=10, null=True, verbose_name='цена'),
        ),
    ]
