# Generated by Django 6.0.2 on 2026-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sliderimage_old_price_sliderimage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена для отображения скидки', max_digits=10, null=True, verbose_name='старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена для отображения скидки', max_digits=10, null=True, verbose_name='старая цена'),
        ),
    ]
