# Generated by Django 6.0.2 on 2026-02-18 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_historicalproduct_old_price_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'группа фильтров',
                'verbose_name_plural': 'группы фильтров',
                'ordering': ['order', 'name'],
                'unique_together': {('slug', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('value', models.CharField(max_length=100, verbose_name='значение для фильтрации')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL-имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.filtergroup', verbose_name='группа фильтров')),
            ],
            options={
                'verbose_name': 'значение фильтра',
                'verbose_name_plural': 'значения фильтров',
                'ordering': ['order', 'name'],
                'unique_together': {('group', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_filters', to='products.filteroption', verbose_name='значение фильтра')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_filters', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'фильтр товара',
                'verbose_name_plural': 'фильтры товаров',
                'unique_together': {('product', 'filter_option')},
            },
        ),
    ]
