# Generated by Django 6.0.2 on 2026-02-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_filtergroup_filteroption_productfilter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filtergroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='filteroption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='filtergroup',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='filteroption',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='filteroption',
            name='value',
        ),
    ]
