# Generated by Django 6.0.2 on 2026-02-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_filtergroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='published_pages',
            field=models.JSONField(blank=True, default=list, help_text='Список страниц для публикации товара: ["women", "men", "children"]', verbose_name='страницы публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_pages',
            field=models.JSONField(blank=True, default=list, help_text='Список страниц для публикации товара: ["women", "men", "children"]', verbose_name='страницы публикации'),
        ),
    ]
