# Generated by Django 6.0.2 on 2026-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_historicalproduct_published_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество на складе'),
        ),
    ]
