# Generated by Django 6.0.2 on 2026-02-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='suppliers.suppliercontract', verbose_name='договор'),
        ),
        migrations.AlterField(
            model_name='suppliercontract',
            name='status',
            field=models.ForeignKey(default='draft', on_delete=django.db.models.deletion.PROTECT, related_name='Contracts', to='suppliers.contractstatus', verbose_name='статус'),
        ),
    ]
