# Generated by Django 6.0.2 on 2026-02-28 17:25

import django.db.models.deletion
import suppliers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт пользователя'),
        ),
        migrations.AlterField(
            model_name='historicalsuppliercontract',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=suppliers.models.get_default_contract_status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.contractstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='historicalsupplierproductrequest',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=suppliers.models.get_default_request_status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.requeststatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='suppliercontract',
            name='status',
            field=models.ForeignKey(default=suppliers.models.get_default_contract_status, on_delete=django.db.models.deletion.PROTECT, related_name='Contracts', to='suppliers.contractstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='supplierproductrequest',
            name='status',
            field=models.ForeignKey(default=suppliers.models.get_default_request_status, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='suppliers.requeststatus', verbose_name='статус'),
        ),
    ]
