# Generated by Django 6.0.2 on 2026-02-28 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_historicalsupplier_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('manager', 'От менеджера'), ('supplier', 'От поставщика')], default='manager', max_length=20, verbose_name='направление')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='дата прочтения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='suppliers.supplierproductrequest', verbose_name='заявка')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'коммуникация по заявке',
                'verbose_name_plural': 'коммуникации по заявкам',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='suppliers_r_request_c27567_idx'), models.Index(fields=['direction'], name='suppliers_r_directi_02915c_idx')],
            },
        ),
    ]
