# Generated by Django 6.0.2 on 2026-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_requestcommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplierproductrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'Женщинам'), ('men', 'Мужчинам'), ('children', 'Детям')], help_text='Категория, на странице которой будет отображаться товар', max_length=20, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='historicalsupplierproductrequest',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='Список URL загруженных изображений товара', verbose_name='изображения товара'),
        ),
        migrations.AddField(
            model_name='supplierproductrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'Женщинам'), ('men', 'Мужчинам'), ('children', 'Детям')], help_text='Категория, на странице которой будет отображаться товар', max_length=20, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='supplierproductrequest',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='Список URL загруженных изображений товара', verbose_name='изображения товара'),
        ),
    ]
