# Generated by Django 6.0.2 on 2026-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_historicalsupplierproductrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplierproductrequest',
            name='suggested_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена товара, которую указывает поставщик', max_digits=10, null=True, verbose_name='предложенная старая цена'),
        ),
        migrations.AddField(
            model_name='supplierproductrequest',
            name='suggested_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена товара, которую указывает поставщик', max_digits=10, null=True, verbose_name='предложенная старая цена'),
        ),
    ]
